helmCharts:
- name: backstage
  namespace: backstage
  version: 0.0.13
  repo: https://ortelius.github.io/backstage
  releaseName: backstage
  includeCRDs: true
  valuesInline:
    app:
      image:
        repository: ghcr.io/ortelius/backstage/app
        tag: "0.0.1"
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        hosts:
          - backstage.ortelius.io
    backend:
      image:
        repository: ghcr.io/ortelius/backstage/backend
        tag: "0.0.1"
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        hosts:
          - backstage-backend.ortelius.io
    psql:
      connectionString:
        secret: postgres-secrets
        key: POSTGRES_CONNECTION_STRING
      host: postgresql.postgresql.svc
      database: backstage
      port: 5432
      username: backstage
      password:
        secret: postgres-secrets
        key: POSTGRES_PASSWORD
    appConfig:
      app:
        title: Ortelius Backstage
        baseUrl: https://backstage.ortelius.io
      organization: {}
      backend:
        baseUrl: https://backstage-backend.ortelius.io
        listen:
          port: 7007
        cors:
          origin: https://backstage.ortelius.io
          methods: [GET, POST, PUT, DELETE]
          credentials: true
        database:
          client: pg
          connection:
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            database: backstage
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
          ensureExists: false
          pluginDivisionMode: schema
          knexConfig:
            pool:
              min: 15
              max: 30
              acquireTimeoutMillis: 60000
              createTimeoutMillis: 30000
              destroyTimeoutMillis: 5000
              idleTimeoutMillis: 60000
              reapIntervalMillis: 1000
              createRetryIntervalMillis: 200
              propagateCreateError: false
      techdocs:
        builder: external
