helmCharts:
- name: backstage
  namespace: backstage
  version: 0.0.22
  repo: https://ortelius.github.io/backstage
  releaseName: backstage
  includeCRDs: true
  valuesInline:
    app:
      image:
        repository: ghcr.io/ortelius/backstage/app
        tag: "0.0.1"
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        hosts:
          - backstage.ortelius.io
        tls:
        - hosts:
          - backstage.ortelius.io
          secretName: app-tls-cert
    backend:
      image:
        repository: ghcr.io/ortelius/backstage/backend
        tag: "0.0.1"
        pullPolicy: Always
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        hosts:
          - backstage-backend.ortelius.io
        tls:
        - hosts:
          - backstage.ortelius.io
          secretName: backend-tls-cert
    psql:
      connectionString:
        secret: postgres-secrets
        key: POSTGRES_CONNECTION_STRING
      host: postgresql.postgresql.svc
      port: 5432
      username: backstage
      password:
        secret: postgres-secrets
        key: POSTGRES_PASSWORD
    appConfig:
      app:
        title: Ortelius Backstage
        baseUrl: https://backstage.ortelius.io
      organization:
        name: Ortelius Dev
      auth:
        environment: production
        providers:
          github:
            development:
              clientId: ${GITHUB_OAUTH_CLIENT_ID}
              clientSecret: ${GITHUB_OAUTH_CLIENT_SECRET}
          integrations:
            github:
              - host: github.com
                apps:
                  - $include: github-app-credentials.yaml
      backend:
        baseUrl: https://backstage-backend.ortelius.io
        listen:
          port: 7007
        cors:
          origin: https://backstage.ortelius.io
          methods: [GET, POST, PUT, DELETE]
          credentials: true
        database:
          client: pg
          connection:
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
          knexConfig:
            pool:
              min: 15
              max: 30
              acquireTimeoutMillis: 60000
              createTimeoutMillis: 30000
              destroyTimeoutMillis: 5000
              idleTimeoutMillis: 60000
              reapIntervalMillis: 1000
              createRetryIntervalMillis: 200
              propagateCreateError: false
      kubernetes:
        serviceLocatorMethod:
          type: 'multiTenant'
        clusterLocatorMethods:
          - type: 'config'
            clusters:
              - url: ${KUBERNETES_URL}
                name: aks
                serviceAccountToken: ${KUBERNETES_TOKEN}
                authProvider: 'serviceAccount'
                skipTLSVerify: true
                skipMetricsLookup: true
      proxy:
        '/argocd/api':
          target: ${ARGOCD_BASE_URL}/api/v1/
          changeOrigin: true
          secure: false
          headers:
            Cookie:
              $env: ${ARGOCD_AUTH_TOKEN}
        '/prometheus/api':
          target: http://kube-prometheus-stack-prometheus.observability:9090/api/v1
      argocd:
        username: ${ARGOCD_USERNAME}
        password: ${ARGOCD_PASSWORD}
        appLocatorMethods:
          - type: 'config'
            instances:
              - name: production
                url: ${ARGOCD_BASE_URL}
      techdocs:
        builder: 'external'
        generator:
          runIn: 'local'
        publisher:
          type: 'awsS3'
          awsS3:
            bucketName: 'ortelius-techdocs-dev'
            region: ${AWS_DEFAULT_REGION}
            credentials:
              accessKeyId: ${AWS_ACCESS_KEY_ID}
              secretAccessKey: ${AWS_ACCESS_KEY_SECRET}
      catalog:
        import:
          entityFilename: catalog-info.yaml
          pullRequestBranchName: backstage-integration
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/ortelius/ortelius-kubernetes/blob/main/catalog-info.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, Domain, Location, Group]
          - type: url
            target: https://github.com/ortelius/ortelius-kubernetes/blob/main/podtato-head-catalog-info.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, Domain, Location, Group]
          - type: url
            target: https://github.com/ortelius/backstage/blob/main/catalog-info.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, Domain, Location]
          - type: github-org
            target: https://github.com/ortelius
            rules:
              - allow: [Group, User]
