apiVersion: v1
kind: Service
metadata:
  name: chart-1663911321-k6-service
  labels:
    helm.sh/chart: k6-service-0.8.0
    app.kubernetes.io/name: k6-service
    app.kubernetes.io/instance: chart-1663911321
    app.kubernetes.io/version: "0.8.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: k6-service
    app.kubernetes.io/instance: chart-1663911321
