apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ortelius
  namespace: ci-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-created.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-deleted.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-running.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notifications
spec:
  description: Ortelius Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://aks-7e3b88d3.hcp.eastus.azmk8s.io.io
  - namespace: '*'
    server: https://aks-7e3b88d3.hcp.eastus.azmk8s.io:443
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'    
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'    
