apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- argocd-server-ingress.yaml
- argocd-appproject.yaml
- argocd-manager.yaml
- argocd-manager-role.yaml
- argocd-manager-role-binding.yaml
- kustomize-kube-infra-applicationSet.yaml
- podtato-kustomize-appSet.yaml
#- iac-applicationSet.yaml


namespace: ci-cd

patchesStrategicMerge:
- argocd-server-service.yaml
- argocd-cm.yaml
- argocd-notifications-cm.yaml
- argocd-rbac-cm.yaml
- argocd-server-clusterRoleBinding.yaml
- argocd-application-controller-clusterRoleBinding.yaml
- argocd-server-service.yaml

- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-notifications-secret
  $patch: delete
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-secret
  $patch: delete

# images:
# - name: quay.io/argoproj/argocd
#   newName: odysseycloud/argocd

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --insecure
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=argocd-server
