apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- argocd-server-ingress.yaml
- argocd-appproject.yaml

- application-sets/kube-infra.yaml
- application-sets/podtato-head.yaml
- application-sets/ortelius-docs.yaml
- application-sets/ortelius-website.yaml

namespace: ci-cd

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-notifications-cm.yaml

# images:
# - name: quay.io/argoproj/argocd
#   newName: odysseycloud/argocd
