helmCharts:
- name: falco
  namespace: falco
  version: 2.0.2
  repo: https://falcosecurity.github.io/charts
  releaseName: falco
  includeCRDs: true
  valuesInline:
    ebpf:
      enabled: true
      
    falcosidekick:
      enabled: true
      webui:
        enabled: true

    falco:
      grpc:
        enabled: true
      programOutput:
        enabled: true
        program: mail -s "Falco Notification" bradmccoydev@gmail.com
