helmCharts:
- name: keptn
  namespace: keptn
  version: 0.12.0
  repo: https://storage.googleapis.com/keptn-installer
  releaseName: keptn
  includeCRDs: true
  valuesInline: 
    control-plane:
      enabled: true
      apiGatewayNginx:
        type: ClusterIP
        port: 80
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: "false"
        host: "keptn.ortelius.io"
        path: /
        pathType: Prefix
        
    continuous-delivery:
      enabled: true 

- name: helm-service
  namespace: keptn
  version: 0.12.0
  repo: https://storage.googleapis.com/keptn-installer
  releaseName: helm-service
  includeCRDs: true

- name: jmeter-service
  namespace: keptn
  version: 0.12.0
  repo: https://storage.googleapis.com/keptn-installer
  releaseName: jmeter-service
  includeCRDs: true

- name: keptn-terraform-service
  namespace: keptn
  version: 0.12.4
  repo: https://bradmccoydev.github.io/terraform-service
  releaseName: keptn-terraform-service
  includeCRDs: true

- name: keptn-ortelius-service
  namespace: keptn
  version: 0.11.6
  repo: https://ortelius.github.io/keptn-ortelius-service
  releaseName: keptn-ortelius-service
  includeCRDs: true
