helmCharts:
- name: kube-prometheus-stack
  namespace: observability
  version: 36.0.2
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  includeCRDs: true
  valuesInline: 
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        hosts:
          - grafana.ortelius.io

      adminPassword: prom-operator

      sidecar:
        dashboards:
          enabled: "true"
          provider:
            allowUiUpdates: true
            disableDeletion: false
            editabled: true

      plugins:
        - digrich-bubblechart-panel
        - grafana-clock-panel
        - grafana-piechart-panel

      additionalDataSources:
        - name: loki
          url: http://loki-stack.observability:3100/
          type: loki
          access: proxy

      persistence:
        type: pvc
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 10Gi

    coreDns:
      enabled: false

    kubeDns:
      enabled: true

    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: prometheus-ingress-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        hosts:
          - prometheus.ortelius.io

      prometheusSpec:
        retention: 7d
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        enableAdminAPI: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi

    prometheusOperator:
      enabled: true
      admissionWebhooks:
        enabled: false
      tls:
        enabled: false
