helmCharts:
- name: kube-prometheus-stack
  namespace: observability
  version: 43.3.1
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  includeCRDs: true
  valuesInline:
    commonLabels:
      backstage.io/kubernetes-id: kube-prometheus-stack
      ortelius.io/repo: ortelius-kubernetes
    grafana:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: prometheus-ingress-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        hosts:
          - prometheus.ortelius.io
      prometheusSpec:
        priorityClassName: "observability-high-priority"
        retention: 7d
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        enableAdminAPI: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi

    prometheusOperator:
      enabled: true
      hostNetwork: false

      admissionWebhooks:
        enabled: false
      tls:
        enabled: false

    coreDns:
      enabled: false
    kubeDns:
      enabled: true
