helmCharts:
- name: kube-prometheus-stack
  namespace: observability
  version: 41.9.1
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  includeCRDs: true
  valuesInline:
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: prometheus-ingress-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        hosts:
          - prometheus.ortelius.io
      prometheusSpec:
        priorityClassName: "observability-high-priority"
        retention: 7d
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        enableAdminAPI: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              #storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi

    prometheusOperator:
      enabled: true
      hostNetwork: false

      admissionWebhooks:
        enabled: false
      tls:
        enabled: false

    grafana:
      #defaultDashboardsTimezone: America/Detroit

      datasources:
        enabled: true
        defaultDatasourceEnabled:
        uid: prometheus
        url: http://kube-prometheus-stack-prometheus.observability:9090

      additionalDataSources:
        - name: loki
          url: http://loki-stack.observability:3100/
          type: loki
          access: proxy

      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: prometheus-ingress-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        hosts:
          - grafana.ortelius.io

      sidecar:
        dashboards:
          enabled: "true"
          provider:
            allowUiUpdates: true
            disableDeletion: false
            editabled: true

      plugins:
        - grafana-clock-panel
        - grafana-piechart-panel

      persistence:
        type: pvc
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 10Gi

    coreDns:
      enabled: false

    kubeDns:
      enabled: true
