apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-prometheus-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-prometheus-service
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn
