apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: admin
  description: Admin
spec:
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Platform
  description: Platform
spec:
  owner: user:guest
  domain: admin
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ingress-nginx
  description: Ortelius Cluster Ingress
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      title: Artifact Hub
      icon: dashboard
    - url: https://www.nginx.com/products/nginx-ingress-controller/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    backstage.io/kubernetes-id: ingress-nginx
    argocd/app-name: ingress-nginx
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/kube-prometheus-stack
    - component:default/jaeger
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kube-prometheus-stack
  description: Ortelius Grafana Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      title: Artifact Hub
      icon: dashboard
    - url: https://prometheus-operator.dev/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: kube-prometheus-stack
    backstage.io/kubernetes-id: kube-prometheus-stack
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/ingress-nginx
    - component:default/cert-manager
    - component:default/external-dns
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argo-rollouts
  description: Ortelius Argo Rollouts
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/argo/argo-rollouts
      title: Artifact Hub
      icon: dashboard
    - url: https://argoproj.github.io/argo-rollouts/features/helm/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: argo-rollouts
    backstage.io/kubernetes-id: argo-rollouts
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  description: Ortelius Argo CD Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/argo/argo-cd
      title: Artifact Hub
      icon: dashboard
    - url: https://argoproj.github.io/cd/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: argocd
    backstage.io/kubernetes-id: argocd
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Ortelius Backstage Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/deliveryhero/backstage
      title: Artifact Hub
      icon: dashboard
    - url: https://backstage.io/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: backstage
    backstage.io/kubernetes-id: backstage
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
    - component:default/postgresql
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jaeger
  description: Ortelius Jaeger Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/jaegertracing/jaeger
      title: Artifact Hub
      icon: dashboard
    - url: https://www.jaegertracing.io/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: jaeger
    backstage.io/kubernetes-id: jaeger
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loki-stack
  description: Ortelius Loki-Stack Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/grafana/loki-stack
      title: Artifact Hub
      icon: dashboard
    - url: https://grafana.com/oss/loki/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: loki-stack
    backstage.io/kubernetes-id: loki-stack
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: opentelemetry-collector
  description: Ortelius Openelemetry Collector Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector
      title: Artifact Hub
      icon: dashboard
    - url: https://opentelemetry.io/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: opentelemetry-collector
    backstage.io/kubernetes-id: opentelemetry-collector
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ortelius-docs
  description: Ortelius Docs
  links:
    - url: https://github.com/ortelius/ortelius-docs
      title: GitHub
      icon: dashboard
    - url: https://docs.ortelius.io/guides/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-docs
    github.com/project-readme-path: README.md
    argocd/app-name: ortelius-docs
    backstage.io/kubernetes-id: ortelius-docs
    backstage.io/techdocs-ref: dir:.
  tags:
    - website
    - documentation
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ortelius-www
  description: Ortelius Website
  links:
    - url: https://github.com/ortelius/ortelius
      title: GitHub
      icon: dashboard
    - url: https://ortelius.io/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: ortelius-www
    backstage.io/kubernetes-id: ortelius-www
    backstage.io/techdocs-ref: dir:.
  tags:
    - website
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgresql
  description: Ortelius postgress SQL Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: http://artifacthub.io/packages/helm/bitnami/postgresql
      title: Artifact Hub
      icon: dashboard
    - url: https://www.postgresql.org/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: postgresql
    backstage.io/kubernetes-id: postgresql
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-dns
  description: Ortelius External DNS Instance
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/bitnami/external-dns
      title: Artifact Hub
      icon: dashboard
    - url: https://https://github.com/kubernetes-sigs/external-dns
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: external-dns
    backstage.io/kubernetes-id: external-dns
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cert-manager
  description: Ortelius Cert Manager
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
      title: Artifact Hub
      icon: dashboard
    - url: https://certmanager.io
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: cert-manager
    backstage.io/kubernetes-id: cert-manager
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8sgpt
  description: K8SGPT
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: Deployment Location GitHub
      icon: dashboard
    - url: https://github.com/k8sgpt-ai/k8sgpt-operator
      title: K8sGPT Project Github
      icon: dashboard
    - url: https://k8sgpt.ai/
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: k8sgpt
    backstage.io/kubernetes-id: k8sgpt
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podtatohead-prod
  description: Podtato Head
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: Deployment Location GitHub
      icon: dashboard
    - url: https://github.com/podtato-head/podtato-head
      title: Podtato Head Project Github
      icon: dashboard
    - url: https://podtatohead.ortelius.io
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: podtatohead-prod
    backstage.io/kubernetes-id: podtatohead-prod
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd