apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podtatohead-prod
  description: Podtato Head Entry
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://github.com/podtato-head/podtato-head
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: podtatohead-prod
    backstage.io/kubernetes-id: podtatohead-prod
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podtatohead-prod
  description: Podtato Head Entry
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://github.com/podtato-head/podtato-head
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: podtatohead-prod
    backstage.io/kubernetes-id: podtatohead-prod
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podtatohead-prod
  description: Podtato Head Entry
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://github.com/podtato-head/podtato-head
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: podtatohead-prod
    backstage.io/kubernetes-id: podtatohead-prod
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/argocd
    - component:default/cert-manager
    - component:default/external-dns
    - component:default/ingress-nginx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podtatohead-left-arm
  description: Podtato Head Left Arm
  links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://github.com/podtato-head/podtato-head
      title: Project Website
      icon: dashboard
  annotations:
    github.com/project-slug: ortelius/ortelius-kubernetes
    github.com/project-readme-path: README.md
    argocd/app-name: podtatohead-prod
    backstage.io/kubernetes-id: podtatohead-prod
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  subcomponentOf:
    - component:default/podtatohead-prod
---
