apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config-map.yaml
- deployment.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
- test-api-connection.yaml

namespace: keptn-jes
