# Source: job-executor-service/templates/jobserviceaccount.yaml
# Role for the jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor-service_job
  namespace: keptn-jes
rules: []
---
# Source: job-executor-service/templates/serviceaccount.yaml
# Role for accessing secrets in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor-service
  namespace: keptn-jes
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "create"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
      - "get"
