apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: observability

patches:
- path: prometheuses-crd.yaml
- path: prometheusagents-crd.yaml
- path: prometheus.yaml
