helmCharts:
- name: testkube
  namespace: test-kube
  version: 1.0.4
  repo: https://kubeshop.github.io/helm-charts
  releaseName: testkube
  includeCRDs: true
  valuesInline:
    prometheus:
      enabled: true