apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "ortelius"
spec:
  stages:
    - name: "non-production"
      sequences:
      - name: "smoke-test"
        tasks:
        - name: "smoke-test"
      - name: "performance-test"
        triggeredOn:
          - event: "non-production.smoke-test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "load-test"
        - name: "evaluation"
        - name: "git-promotion"
        - name: "catalog"
      - name: "integration-test"
        triggeredOn:
          - event: "non-production.performance-test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
        - name: "git-promotion"
        - name: "catalog"
      - name: "qa"
        triggeredOn:
          - event: "non-production.integration-test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "evaluation"
        - name: "git-promotion"
        - name: "catalog"
    - name: "production"
      sequences:
      - name: "staging"
        triggeredOn:
          - event: "non-production.qa.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "evaluation"
        - name: "catalog"
      - name: "production"
        triggeredOn:
          - event: "production.staging.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "test"
        - name: "evaluation"
        - name: "catalog"
