apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "ortelius"
spec:
  stages:
    - name: "load-test"
      sequences:
      - name: "smoke-test"
        tasks:
        - name: "smoke-test"
      - name: "load-test"
        triggeredOn:
          - event: "load-test.smoke-test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "load-test"
        - name: "evaluation"
        - name: "git-promotion"
        - name: "catalog"
    - name: "integration-test"
      sequences:
      - name: "integration-test"
        triggeredOn:
          - event: "load-test.load-test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
        - name: "git-promotion"
        - name: "catalog"
    - name: "quality-assurance"
      sequences:
      - name: "qa"
        triggeredOn:
          - event: "integration-test.integration-test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
        - name: "git-promotion"
        - name: "catalog"
    - name: "staging"
      sequences:
      - name: "staging"
        triggeredOn:
          - event: "quality-assurance.qa.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "evaluation"
        - name: "catalog"
    - name: "production"
      sequences:
      - name: "production"
        triggeredOn:
          - event: "staging.staging.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "test"
        - name: "evaluation"
        - name: "catalog"
