apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "ortelius"
spec:
  stages:
    - name: "load"
      sequences:
      - name: "smoke"
        tasks:
        - name: "smoke-test"
      - name: "test"
        triggeredOn:
          - event: "load.smoke.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "load-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"
        - name: "catalog"
    - name: "int"
      sequences:
      - name: "test"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"
        - name: "catalog"
    - name: "qa"
      sequences:
      - name: "test"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"
        - name: "catalog"
    - name: "stag"
      sequences:
      - name: "test"
        tasks:
        - name: "api-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "catalog"
    - name: "prod"
      sequences:
      - name: "test"
        tasks:
        - name: "test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "catalog"
      - name: "remediation"
        triggeredOn:
          - event: "prod.remediation.finished"
            selector:
              match:
                evaluation.result: "fail"
        tasks:
          - name: "get-action"
          - name: "action"
          - name: "evaluation"
            triggeredAfter: "15m"
            properties:
              timeframe: "15m"
    - name: "rollback"
      sequences:
        - name: "revert"
          triggeredOn:
            - event: "load.test.finished"
              selector:
                match:
                  evaluation.result: "fail"
            - event: "int.test.finished"
              selector:
                match:
                  evaluation.result: "fail"
            - event: "qa.test.finished"
              selector:
                match:
                  evaluation.result: "fail"
            - event: "stag.test.finished"
              selector:
                match:
                  evaluation.result: "fail"
            - event: "prod.test.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "rollback"
