helmCharts:
- name: cert-manager
  version: 1.11.0
  namespace: dns-infra
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  valuesInline:
    installCRDs: true
    rbac:
      create: true
