apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-prometheus-service
  namespace: keptn
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
