helmCharts:
- name: ingress-nginx
  version: 4.6.1
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: dns-infra
  includeCRDs: true
  valuesInline:
    commonLabels:
      backstage.io/kubernetes-id: ingress-nginx
      ortelius.io/repo: ortelius-kubernetes
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx-ingress
                - key: component
                  operator: In
                  values:
                    - controller
              topologyKey: "kubernetes.io/hostname"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
      publishService:
        enabled: true
      replicaCount: 1
      stats:
        enabled: true

    rbac:
      create: true

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-ssl-passthrough
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=ingress-nginx
