helmCharts:
- name: ingress-nginx
  version: 4.4.2
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: dns-infra
  includeCRDs: true
  valuesInline:
    commonLabels:
      backstage.io/kubernetes-id: ingress-nginx
    controller:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx-ingress
                - key: component
                  operator: In
                  values:
                    - controller
              topologyKey: "kubernetes.io/hostname"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
      publishService:
        enabled: true
      replicaCount: 1
      stats:
        enabled: true

    rbac:
      create: true

    service:
      externalTrafficPolicy: Local

    config:
      use-forwarded-headers: "true"
      enable-opentracing: "true"
      jaeger-collector-host: jaeger-agent.observability.svc.cluster.local

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-ssl-passthrough
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=ingress-nginx
