helmCharts:
- name: ortelius-docs
  namespace: ortelius
  version: 10.0.15
  repo: https://ortelius.github.io/ortelius-docs
  releaseName: ortelius-docs
  includeCRDs: true
  valuesInline:
    service:
      port: 80
      serviceMonitor:
        enabled: false
    ingress:
      enabled: true
      host: docs.ortelius.io
      path: /
      pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    keptnLabels:
      keptnProject: ortelius
      keptnService: docs
      keptnStage: prd
