helmCharts:
- name: ortelius-docs
  namespace: ortelius-docs
  version: 10.0.1
  repo: https://ortelius.github.io/ortelius-docs
  releaseName: ortelius-docs
  includeCRDs: true
  valuesInline:
    ingress:
      enabled: true
      host: docs.ortelius.io
