helmCharts:
- name: ortelius-docs
  namespace: ortelius
  version: 10.0.15
  repo: https://ortelius.github.io/ortelius-docs
  releaseName: ortelius-docs
  includeCRDs: true
  valuesInline:
    DockerRepo: "quay.io/ortelius/ortelius-docs"
    DockerTag: "main-v10.0.0.160-g5f573cc"
    service:
      serviceMonitor:
        enabled: false
    ingress:
      enabled: true
      host: docs.ortelius.io
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    keptnLabels:
      keptnProject: ortelius
      keptnService: docs
      keptnStage: prd
