apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: observability

patchesStrategicMerge:
- prometheuses-crd.yaml
- grafana-ingress.yaml
- prometheus-ingress.yaml
#- prometheus-pvc.yaml
