apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-read-secret-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - watch
      - list
