apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-prometheus-sli-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-read-secret-prometheus
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn
