apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8sgpt
  namespace: ci-cd
  labels:
    backstage.io/kubernetes-id: argocd
    ortelius.io/repo: platform
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/ortelius/ortelius-kubernetes.git
          revision: HEAD
          directories:
          - path: kube-infra/kustomize/ai/k8sgpt
      - list:
          elements:
          - cluster: prod
            url: https://aks-r13astrw.hcp.centralus.azmk8s.io:443
            values:
              CLIENT_ENVIRONMENT: prod
  template:
    metadata:
      name: '{{ path.basename }}'
      annotations:
        environment: prod
        notifications.argoproj.io/subscribe.on-deployed.github: ""
        notifications.argoproj.io/subscribe.on-deployed.grafana: argoDeployed
    spec:
      project: ortelius
      source:
        repoURL: https://github.com/ortelius/ortelius-kubernetes.git
        targetRevision: HEAD
        path: '{{path}}/envs/{{cluster}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
