apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-infra-kustomize-setup
  namespace: ci-cd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/ortelius/ortelius-kubernetes.git
          revision: HEAD
          directories:
          - path: kube-infra/kustomize/ci-cd/*
          - path: kube-infra/kustomize/dns-infra/ingress-nginx
          - path: kube-infra/kustomize/datastore/*
          - path: kube-infra/kustomize/catalog/*
          - path: kube-infra/kustomize/observability/*
          #- path: kube-infra/kustomize/security/falco
          #- path: kube-infra/kustomize/keptn-contrib/*
          #- path: kube-infra/kustomize/demo/*
        exclude:
      - list:
          elements:
          - cluster: prod
            url: https://aks-742d5c8e.hcp.centralus.azmk8s.io:443
            values:
              CLIENT_ENVIRONMENT: prod
  template:
    metadata:
      name: '{{ path.basename }}'
      annotations:
        environment: prod
    spec:
      project: ortelius
      source:
        repoURL: https://github.com/ortelius/ortelius-kubernetes.git
        targetRevision: HEAD
        path: '{{path}}/envs/{{cluster}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
