apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ortelius-podtatohead-stag
  namespace: ci-cd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/ortelius/ortelius-kubernetes.git
          revision: HEAD
          directories:
          - path: kube-infra/kustomize/podtato-head/*
        exclude:
      - list:
          elements:
          - cluster: stag
            url: https://aks-d1a554ae.hcp.centralus.azmk8s.io:443
            values:
              CLIENT_ENVIRONMENT: stag
  template:
    metadata:
      name: 'podtatohead-{{cluster}}'
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.keptn: ""
        notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
        environment: '{{cluster}}'
      labels:
        keptnProject: ortelius
        keptnService: podtatohead
        keptnStage: '{{cluster}}'
        keptnSequence: test
    spec:
      project: ortelius
      source:
        repoURL: https://github.com/ortelius/ortelius-kubernetes.git
        targetRevision: HEAD
        path: '{{path}}/envs/{{cluster}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
