# Source: job-executor-service/templates/jobserviceaccount.yaml
# Bind role for accessing secrets onto the job service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-executor-service_job
  namespace: keptn-jes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-executor-service_job
subjects:
  - kind: ServiceAccount
    name: chart-1664332147-job-executor-service-default-job-account
    namespace: keptn-jes
---
# Source: job-executor-service/templates/serviceaccount.yaml
# Bind role for accessing secrets onto the job-executor-service service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-executor-service
  namespace: keptn-jes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-executor-service
subjects:
  - kind: ServiceAccount
    name: chart-1664332147-job-executor-service
    namespace: keptn-jes
