apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: monitoring

patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        cert-manager.io/cluster-issuer: letsencrypt-development-aws
  target:
    kind: Ingress
    name: prometheus-server
