apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podtato-head
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  rules:
  - host: podtatohead.ortelius.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: podtato-head-entry
            port:
              number: 9000
      - pathType: Prefix
        path: "/load"
        backend:
          service:
            name: podtato-head-entry-load
            port:
              number: 9000
      - pathType: Prefix
        path: "/int"
        backend:
          service:
            name: podtato-head-entry-int
            port:
              number: 9000
      - pathType: Prefix
        path: "/qa"
        backend:
          service:
            name: podtato-head-entry-qa
            port:
              number: 9000
      - pathType: Prefix
        path: "/sta"
        backend:
          service:
            name: podtato-head-entry-stag
            port:
              number: 9000
