helmCharts:
- name: vault
  namespace: vault
  version: 0.20.1
  repo: https://helm.releases.hashicorp.com
  releaseName: vault
  includeCRDs: true
  valuesInline: 
    server:
      injector:
        enabled: false
      dev:
        enabled: true
        devRootToken: "bradmccoy"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          #nginx.ingress.kubernetes.io/auth-type: basic
          #nginx.ingress.kubernetes.io/auth-secret: vault-ingress-auth
          #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        ingressClassName: ""
        pathType: Prefix
        hosts:
          - host: vault.ortelius.io
            paths: []
        extraPaths: []
        tls:
          - secretName: vault-tls-certificate
            hosts:
              - vault.ortelius.io
