helmCharts:
- name: k8sgpt-operator
  namespace: k8sgpt-operator-system
  version: 0.0.17
  repo: https://charts.k8sgpt.ai
  releaseName: k8sgpt-operator
  includeCRDs: true
  valuesInline:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
    grafanaDashboard:
      enabled: false
      folder:
        annotation: grafana_folder
        name: default
      label:
        key: grafana_dashboard
        value: "1"
