helmCharts:
- name: k8sgpt-operator
  namespace: k8sgpt
  version: 0.0.16
  repo: https://charts.k8sgpt.ai
  releaseName: k8sgpt-operator
  includeCRDs: true
  valuesInline:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
