apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: ci-cd
data:
  context: |
    argocdUrl: https://argocd.ortelius.io
  service.webhook.keptn: |
    url: https://keptn.ortelius.io/api/v1/event
    headers:
    - name: x-token
      value: $keptn-x-token
    - name: Content-Type
      value: application/json
  template.keptn-deployed-remove-me: |
    webhook:
      keptn:
        method: POST
        body: |
          {
            "data": {
              "project": "{{.app.metadata.labels.keptnProject}}",
              "service": "{{.app.metadata.labels.keptnService}}",
              "stage": "{{.app.metadata.labels.keptnStage}}"
            },
            "source": "argocd",
            "specversion": "1.0",
            "type": "sh.keptn.event.{{.app.metadata.labels.keptnStage}}.{{.app.metadata.labels.keptnSequence}}.triggered"
          }
  trigger.on-deployed: |
    - when: app.status.sync.status == 'Synced' and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [keptn-deployed]
