apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ortelius
  namespace: ci-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Ortelius Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: aks-d1a554ae.hcp.centralus.azmk8s.io
  - namespace: '*'
    server: aks-d1a554ae.hcp.centralus.azmk8s.io:443
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
