apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://argocd.ortelius.io
  service.webhook.keptn: |
    url: https://keptn.ortelius.io/api/v1/event
    headers:
    - name: x-token
      value: $keptn-x-token
    - name: Content-Type
      value: application/json
  template.keptn-deployed: |
    webhook:
      keptn:
        method: POST
        body: |
          {
            "data": {
              "project": "ortelius",
              "service": "podtatohead",
              "stage": "load"
            },
            "source": "argocd",
            "specversion": "1.0",
            "type": "sh.keptn.event.load.smoke.triggered"
          }
  trigger.on-deployed: |
    - when: app.status.sync.status == 'Synced' and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      send: [keptn-deployed]
