apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- argocd-server-ingress.yaml
- argocd-appproject.yaml
- application-sets/kube-infra.yaml
- application-sets/ortelius-docs.yaml
- application-sets/ortelius-website.yaml
- argocd-service-monitors.yaml

- application-sets/ortelius-podtatohead-load.yaml
- application-sets/ortelius-podtatohead-int.yaml
- application-sets/ortelius-podtatohead-qa.yaml
- application-sets/ortelius-podtatohead-stag.yaml
- application-sets/ortelius-podtatohead-prod.yaml

namespace: ci-cd

patchesStrategicMerge:
- argocd-notifications-cm.yaml
- argocd-server-service.yaml
- argocd-cm.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --insecure
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=argocd-server
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: ci-cd
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argocd-application-controller
    version: v1
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: ci-cd
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argocd-server
    version: v1

# images:
# - name: quay.io/argoproj/argocd
#   newName: odysseycloud/argocd
