apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-infra
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: keptn
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sgpt
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"
---