apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- argocd-server-ingress.yaml
- argocd-appproject.yaml
- argocd-manager.yaml
- argocd-manager-role.yaml
- argocd-manager-role-binding.yaml
- kustomize-kube-infra-applicationSet.yaml

namespace: ci-cd

patchesStrategicMerge:
- argocd-server-service.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml
- argocd-server-clusterRoleBinding.yaml
- argocd-application-controller-clusterRoleBinding.yaml
- argocd-server-service.yaml
- argocd-dex-server-deployment.yaml
- argocd-repo-server.yaml
- argocd-server-deployment.yaml
