apiVersion: builtin
kind: LabelTransformer
metadata:
  name: add-labels
labels:
  env: prod
  instance: kustomize
  keptnProject: ortelius
  keptnService: podtato-head
  keptnStage: prod
fieldSpecs:
  - path: metadata/labels
    create: true
