apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-promotion-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: git-promotion-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: develop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: git-promotion-service
      app.kubernetes.io/instance: keptn
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: git-promotion-service
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: develop
    spec:
      serviceAccountName: keptn-git-promotion-service
      containers:
        - name: git-promotion-service
          imagePullPolicy: Always
          image: bradmccoydev/keptn-git-promotion-service:0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KEPTN_API_URL
              value: 'http://api-gateway-nginx/api'
            - name: GIT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github
                  key: access-token
            - name: KEPTN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keptn-api-token
                  key: keptn-api-token
            - name: EXTERNAL_URL
              value: 'http://api-gateway-nginx/api'
            - name: PUBSUB_URL
              value: nats://keptn-nats
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.git-promotion.>'
