apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  namespace: test
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-rollout-updated.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack: argo-notifications
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    canary:
      # analysis:
      #   templates:
      #   - templateName: success-rate
      #   args:
      #   - name: service-name
      #     value: demo-stable
      canaryService: demo-canary
      stableService: demo-stable
      # trafficRouting:
      #   nginx:
      #     stableIngress: canary-stable
      steps:
      - setCanaryScale:
          replicas: 3
      # a percentage of spec.replicas
      - setCanaryScale:
          weight: 25
      # matchTrafficWeight returns to the default behavior of matching the canary traffic weight
      - setCanaryScale:
          matchTrafficWeight: true
      # - setCanaryScale:
      #     matchTrafficWeight: true
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
