helmCharts:
- name: keptn
  namespace: keptn
  version: 0.19.0
  repo: https://charts.keptn.sh
  releaseName: keptn
  includeCRDs: true
  valuesInline:
    control-plane:
      enabled: true
      apiGatewayNginx:
        type: ClusterIP
        port: 80
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: "false"
        host: "keptn.ortelius.io"
        path: /
        pathType: Prefix

    continuous-delivery:
      enabled: true
