helmCharts:
- name: keptn
  namespace: keptn
  version: 0.19.1
  repo: https://charts.keptn.sh
  releaseName: keptn
  includeCRDs: true
  valuesInline:
    control-plane:
      enabled: true


    continuous-delivery:
      enabled: true
