apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres-debug
    environment: debug
  name: postgres-debug
  namespace: postgres
spec:
  containers:
  - image: alpine:3.16
    name: debug
    args:
    - sleep
    - "86400"
