helmCharts:
- name: external-secrets
  namespace: security
  version: 0.8.1
  repo: https://charts.external-secrets.io
  releaseName: external-secrets-operator
  includeCRDs: true
  valuesInline:
    podLabels:
      backstage.io/kubernetes-id: external-secrets
    certContoller:
      serviceMonitor:
        enabled: true
        interval: "30s"
        scrapeTimeout:  "25s"
        additionalLabels:
            release: kube-prometheus-stack
      webhook:
        serviceMonitor:
          enabled: true
          interval: "30s"
          scrapeTimeout:  "25s"
          additionalLabels:
            release: kube-prometheus-stack
