helmCharts:
- name: grafana
  namespace: observability
  version: 6.50.7
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  includeCRDs: true
  valuesInline:
    extraLabels:
      backstage.io/kubernetes-id: grafana
      ortelius.io/repo: ortelius/ortelius-kubernetes
    admin:
      existingSecret: "admin"
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    plugins:
      - grafana-github-datasource
      - grafana-clock-panel
      - grafana-piechart-panel

    datasources:
      datasources.yaml:
        apiVersion: 1
        version: 1
        editable: true
        datasources:
          - name: Prometheus
            type: prometheus
            uid: 1
            url: http://kube-prometheus-stack-prometheus.observability:9090
            isDefault: true
          - name: Alert Manager
            type: alertmanager
            uid: 2
            url: http://kube-prometheus-stack-alertmanager.observability:9093
            isDefault: false
            jsonData:
              implementation: prometheus
          - name: Jaeger
            type: jaeger
            uid: 3
            url: http://jaeger-tracing-query.observability.svc.cluster.local:80
            isDefault: false
          - name: Loki
            type: loki
            uid: 4
            url: http://loki-stack.observability:3100
            isDefault: false

    sidecar:
      dashboards:
        enabled: "true"
        provider:
          allowUiUpdates: true
          disableDeletion: false
      alerts:
        enabled: true
        label: grafana_alert

    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'default'
         orgId: 1
         folder: ''
         type: file
         disableDeletion: false
         editable: true
         options:
           path: /var/lib/grafana/dashboards/default
       - name: 'admin'
         orgId: 1
         folder: 'admin'
         type: file
         disableDeletion: false
         editable: false
         options:
           path: /var/lib/grafana/dashboards/admin

    dashboards:
      default:
        ingress-nginx:
          url: https://grafana.com/api/dashboards/9614/revisions/1/download

    grafana.ini:
      log:
        level: debug

      server:
        root_url: https://grafana.ortelius.io

    serviceMonitor:
      enabled: true
      path: /metrics
      labels:
        release: kube-prometheus-stack
