helmCharts:
- name: grafana
  namespace: observability
  version: 6.56.2
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  includeCRDs: true
  valuesInline:
    extraLabels:
      backstage.io/kubernetes-id: grafana
      ortelius.io/repo: ortelius-kubernetes
    admin:
      existingSecret: grafana-secrets
      userKey: admin-user
      passwordKey: admin-password

    persistence:
      type: pvc
      enabled: false
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - cloudspout-button-panel
      - grafana-github-datasource

    sidecar:
      dashboards:
        enabled: "true"
        provider:
          allowUiUpdates: true
          disableDeletion: false
      alerts:
        enabled: true
        label: grafana_alert
      datasources:
        enabled: true

    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'default'
         orgId: 1
         folder: ''
         type: file
         disableDeletion: false
         editable: true
         options:
           path: /var/lib/grafana/dashboards/default
       - name: 'platform'
         orgId: 1
         folder: 'Platform'
         type: file
         disableDeletion: false
         editable: false
         options:
           path: /var/lib/grafana/dashboards/platform

    dashboards:
      default:
        ingress-nginx:
          url: https://grafana.com/api/dashboards/9614/revisions/1/download
      platform:
        ingress-nginx:
          url: https://grafana.com/api/dashboards/9614/revisions/1/download

    extraSecretMounts:
      - name: grafana-secrets
        mountPath: /etc/secrets/grafana_secrets
        secretName: grafana-secrets
        readOnly: true

    grafana.ini:
      log:
        level: debug

      server:
        root_url: https://grafana.ortelius.io

      smtp:
        enabled: false

    serviceMonitor:
      enabled: true
      path: /metrics
      labels:
        release: kube-prometheus-stack
