repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

values:
  - argo-cd:
      enabled: true 
      
environments:
  production:
    values:
      - argo-cd:
          enabled: true

releases:
  - name: argo-cd
    namespace: ci-cd
    chart: argo/argo-cd
    version: 3.26.5
    condition: argo-cd.enabled
    values:
      -  ../kube-infra/ci-cd/argo-cd/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-argo-cd-values.yaml

  - name: argocd-applicationset
    namespace: ci-cd
    chart: argo/argocd-applicationset
    version: 0.2.0
    condition: argo-cd.enabled 
    values:
      - ../kube-infra/ci-cd/argocd-applicationset/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-argocd-applicationset-values.yaml 

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 3.34.0
    values:
      - ../kube-infra/dns-infra/ingress-nginx/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-ingress-nginx-values.yaml 