apiVersion: v1
kind: Service
metadata:
  name: git-promotion-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: git-promotion-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: git-promotion-service
    app.kubernetes.io/instance: keptn
