helmCharts:
- name: cdevents-controller
  version: 0.0.5
  repo: https://bradmccoydev.github.io/cdevents-controller
  releaseName: cdevents-controller
  namespace: cdevents
  includeCRDs: true
  valuesInline:
    logLevel: debug
    image:
      repository: ghcr.io/bradmccoydev/cdevents-controller
      tag: sha-f9802a70
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-development-aws
      hosts:
        - host: cdevents.bradmccoy.io
          paths:
            - path: /
              pathType: Prefix
      tls:
       - secretName: cdevents-tls
         hosts:
           - cdevents.bradmccoy.io

- name: mongodb
  version: 13.15.1
  namespace: cdevents
  repo: https://charts.bitnami.com/bitnami
  releaseName: mongodb
  valuesInline:
    commonLabels:
      backstage.io/kubernetes-id: mongodb
      ortelius.io/repo: ortelius-kubernetes  
    architecture: standalone
    replicaCount: 1
    extraEnvVars:
      - name: LOG_LEVEL
        value: debug
    global:
      namespaceOverride: cdevents
    auth:
      enabled: false
      rootUser: root
      existingSecret: mongodb
      usernames:
        - cdevents
      databases: 
        - cdevents
