helmCharts:
- name: ortelius-www
  namespace: ortelius
  version: 9.0.0-build.295
  repo: https://ortelius.github.io/website
  releaseName: ortelius-www
  includeCRDs: true
  valuesInline:
    DockerRepo: "quay.io/ortelius/website"
    DockerTag: "main-v9.0.0.334-gcd73761"
    ingress:
      enabled: true
      host: ortelius.io
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
