apiVersion: builtin
kind: LabelTransformer
metadata:
  name: add-labels
labels:
  env: production
  instance: kustomize
  keptnProject: ortelius
  keptnService: podtato-head
  keptnStage: production
fieldSpecs:
  - path: metadata/labels
    create: true
