apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podtato-head
  namespace: ci-cd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/ortelius/ortelius-kubernetes.git
          revision: HEAD
          directories:
          - path: kube-infra/kustomize/podtato-head/*
        exclude:
      - list:
          elements:
          - cluster: development
            url: https://58FFA2BB4C6C5B798E6BA3229F902277.gr7.us-west-2.eks.amazonaws.com
            values:
              CLIENT_ENVIRONMENT: development
  template:
    metadata:
      name: 'podtato-head'
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.keptn: ""
        notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
        environment: development
      labels:
        keptnProject: ortelius
        keptnService: podtato-head
        keptnStage: dev
    spec:
      project: ortelius
      source:
        repoURL: https://github.com/ortelius/ortelius-kubernetes.git
        targetRevision: HEAD
        path: '{{path}}/overlays/{{cluster}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
