helmCharts:
- name: jaeger
  namespace: observability
  version: 0.71.2
  repo: https://jaegertracing.github.io/helm-charts
  releaseName: jaeger
  includeCRDs: true
  valuesInline:
    nameOverride: "tracing"
    provisionDataStore:
      elasticsearch: true
    storage:
      type: elasticsearch
    query:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    agent:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    collector:
      enabled: true
      autoscaling:
        enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
