helmCharts:
- name: jaeger
  namespace: observability
  version: 0.64.2
  repo: https://jaegertracing.github.io/helm-charts
  releaseName: jaeger
  includeCRDs: true
  valuesInline:
    provisionDataStore:
      elasticsearch: true
    storage:
      type: elasticsearch
    collector:
      autoscaling:
        enabled: true
    query:
      enabled: true
