apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.0/manifests/install.yaml
- argocd-manager-role-binding.yaml
- argocd-manager-role.yaml
- argocd-manager.yaml
- priority-class.yaml

namespace: ci-cd

patchesStrategicMerge:
- argocd-rbac-cm.yaml

- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-notifications-secret
  $patch: delete
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-secret
  $patch: delete
