apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.12/manifests/install.yaml
- argocd-manager-role-binding.yaml
- argocd-manager-role.yaml
- argocd-manager.yaml
- argocd-service-monitors.yaml

namespace: ci-cd

patchesStrategicMerge:
- argocd-server-service.yaml
- argocd-rbac-cm.yaml

- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-notifications-secret
  $patch: delete
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: argocd-secret
  $patch: delete

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --insecure
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=argocd-server
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: ci-cd
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argocd-application-controller
    version: v1
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: ci-cd
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argocd-server
    version: v1
