apiVersion: v1
kind: Service
metadata:
  name: chart-1662850918-prometheus-service
  labels:
    helm.sh/chart: prometheus-service-0.0.1
    app.kubernetes.io/name: prometheus-service
    app.kubernetes.io/instance: chart-1662850918
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-service
    app.kubernetes.io/instance: chart-1662850918
